### ISSUE TITLE
Seminario1-revAngelo

### ISSUE THREAD

**Issue by angelogluz** [virtual-pub/Virtual-pub-web#2]
## Correções

- [x] Colocar em negrito na wiki as keywords do projeto para auxiliar a apresentação
- [x] Adicionar escrita do relatório e artigo no cronograma

## Anotações/Considerações

- Estudar bastente os sistemas similares

**Comment by vinibacc** [comment]
Alguns sistemas que tive como base do meu projeto
[Vivino](https://www.vivino.com/)
[Facebook](https://www.facebook.com/)
[Twitter](https://twitter.com/)
